spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wwwcodcom
    url: jdbc:mysql://127.0.0.1:3306/template?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null
  cache:
    type: REDIS
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 2ms
        min-idle: 0
server:
  port: 8081


#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug


#logging:
#  level:
#    com.imooc.dataobject.mapper: trace
mybatis:
  config-location: classpath:/mybatis-config.xml
